export const SAVE_CAT_BREEDS = 'SAVE_CAT_BREEDS';
export const ADD_CAT_IMAGE = 'ADD_CAT_IMAGE';
export const LOGIN_USER = 'LOGIN_USER';
export const SAVE_RANDOM_PIC = 'SAVE_RANDOM_PIC';
export const ADD_IMAGE_TO_FAVORITE = 'ADD_IMAGE_TO_FAVORITE';
export const DELETE_IMAGE_FROM_FAVORITE = 'DELETE_IMAGE_FROM_FAVORITE';
export const INVALID_LOGIN = 'INVALID_LOGIN';
export const LOGOUT_USER = 'LOGOUT_USER';
export const COPY_IMAGE_TO_CLIPBOARD = 'COPY_IMAGE_TO_CLIPBOARD';
export const LOAD_EXPLORE_IMAGES = 'LOAD_EXPLORE_IMAGES';
export const WELCOME_USER = 'WELCOME_USER';
export const CLEAR_INFO = 'CLEAR_INFO';
export const LOG_OUT_INFO = 'LOG_OUT_INFO';
export const SIGN_UP_USER = 'SIGN_UP_USER';

