export const SAVE_CAT_BREEDS = 'SAVE_CAT_BREEDS';
export const ADD_CAT_IMAGE = 'ADD_CAT_IMAGE';
export const LOGIN_USER = 'LOGIN_USER';
export const SAVE_RANDOM_PIC = 'SAVE_RANDOM_PIC';
export const ADD_IMAGE_TO_FAVORITE = 'ADD_IMAGE_TO_FAVORITE';
export const DELETE_IMAGE_FROM_FAVORITE = 'DELETE_IMAGE_FROM_FAVORITE';